### ISSUE TITLE
Штааааа???!

### ISSUE THREAD

**Issue by dsbabkov** [gil9red/DownloadByPornSite#1]
))))

**Comment by gil9red** [comment]
хех :D

**Comment by dsbabkov** [comment]
Блин, а можно как-то удалить эту иссю, а то у меня на главной странице теперь репозиторий в контрибьютерном списке))

**Comment by gil9red** [comment]
не нашел такой кнопки, а гугл не помог :)

**Comment by dsbabkov** [comment]
Ну вот, моё имя теперь опорочено поддержкой подпольных проектов :)
Это heaven, если что :)
